name: HelloWorld

author: Joe Dean

main: helloworld.HelloWorld

commands:
    helloworld:
        description: Simple hello world app.  Type "helloworld" at minecraft command prompt and see custom message.
    helloworld_admin:
        description: Type "helloworld" and see a message.

version: 0.1

